# Generated by Django 3.0.3 on 2020-09-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toppings_in_pizza', '0002_toppingsinpizza_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingsinpizza',
            name='author',
        ),
    ]
