# Generated by Django 3.0.3 on 2020-09-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_pizza', models.IntegerField()),
                ('vote_mark', models.IntegerField()),
            ],
        ),
    ]
