# Generated by Django 3.0.3 on 2020-09-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id_user',
        ),
        migrations.AddField(
            model_name='vote',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='id_pizza',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_mark',
            field=models.PositiveIntegerField(),
        ),
    ]
