# Generated by Django 3.0.3 on 2020-09-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_remove_pizza_average_mark'),
        ('votes', '0002_auto_20200913_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id_pizza',
        ),
        migrations.AddField(
            model_name='vote',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
            preserve_default=False,
        ),
    ]
