# Generated by Django 3.0.3 on 2020-09-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20200913_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_mark',
        ),
    ]
