# Generated by Django 3.0.3 on 2020-09-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='average_mark',
        ),
    ]
