# Generated by Django 3.0.3 on 2020-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_remove_pizza_average_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='votes_num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
