# Generated by Django 3.0.3 on 2020-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_pizza_votes_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='votes_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
