# Generated by Django 3.0.3 on 2020-09-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20200914_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='votes_num',
        ),
    ]
