# Generated by Django 3.0.3 on 2020-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_remove_pizza_votes_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
